/**
 * Referensi Standar Kependudukan & Pencatatan Sipil (Dukcapil)
 * Berdasarkan Permendagri No. 109 Tahun 2019
 */

export const DAFTAR_PEKERJAAN_DUKCAPIL: string[] = [
  'Belum / Tidak Bekerja',
  'Mengurus Rumah Tangga',
  'Pelajar / Mahasiswa',
  'Pensiunan',
  'Pegawai Negeri Sipil (PNS)',
  'Tentara Nasional Indonesia (TNI)',
  'Kepolisian RI (POLRI)',
  'Perdagangan',
  'Petani / Pekebun',
  'Peternak',
  'Nelayan / Perikanan',
  'Industri',
  'Konstruksi',
  'Transportasi',
  'Karyawan Swasta',
  'Karyawan BUMN',
  'Karyawan BUMD',
  'Karyawan Honorer',
  'Buruh Harian Lepas',
  'Buruh Tani / Perkebunan',
  'Buruh Nelayan / Perikanan',
  'Buruh Peternakan',
  'Pembantu Rumah Tangga',
  'Tukang Cukur',
  'Tukang Listrik',
  'Tukang Batu',
  'Tukang Kayu',
  'Tukang Sol Sepatu',
  'Tukang Las / Pandai Besi',
  'Tukang Jahit',
  'Penata Rambut',
  'Penata Rias',
  'Penata Busana',
  'Mekanik',
  'Seniman',
  'Tabib',
  'Paraji',
  'Perancang Busana',
  'Penterjemah',
  'Imam Masjid',
  'Pendeta',
  'Pastor',
  'Wartawan',
  'Ustadz / Mubaligh',
  'Juru Masak',
  'Promotor Acara',
  'Anggota DPR-RI',
  'Anggota DPD',
  'Anggota BPK',
  'Presiden',
  'Wakil Presiden',
  'Anggota Mahkamah Konstitusi',
  'Anggota Kabinet / Kementerian',
  'Duta Besar',
  'Gubernur',
  'Wakil Gubernur',
  'Bupati',
  'Wakil Bupati',
  'Walikota',
  'Wakil Walikota',
  'Anggota DPRD Provinsi',
  'Anggota DPRD Kabupaten / Kota',
  'Dosen',
  'Guru',
  'Pilot',
  'Pengacara',
  'Notaris',
  'Arsitek',
  'Akuntan',
  'Konsultan',
  'Dokter',
  'Bidan',
  'Perawat',
  'Apoteker',
  'Psikiater / Psikolog',
  'Penyiar Televisi',
  'Penyiar Radio',
  'Pelaut',
  'Peneliti',
  'Sopir',
  'Pialang',
  'Paranormal',
  'Pedagang',
  'Perangkat Desa',
  'Kepala Desa',
  'Biarawati',
  'Wiraswasta',
  'Lainnya',
]

export const STATUS_HUBUNGAN_KELUARGA: string[] = [
  'Kepala Keluarga',
  'Suami',
  'Istri',
  'Anak',
  'Ayah',
  'Ibu',
  'Menantu',
  'Cucu',
  'Orang Tua',
  'Mertua',
  'Famili Lain',
  'Pembantu',
  'Lainnya',
]

export const STATUS_KEPENDUDUKAN_LIST: string[] = [
  'Tetap',
  'Pendatang',
  'Pendatang Sementara',
  'Pindah',
  'Meninggal',
]

